/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head';
import { Title } from '../components/Title';
import { TableBig } from '../components/TableBig';
import styles from '../styles/pages/agenda.module.scss';
import Link from 'next/link';
import { TableSmall } from '../components/TableSmall';

export default function Agenda() {
  return (
    <>
      <Head>
        <title>Agenda Tributária</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={`${styles.agenda} container content`}>
        <Title title="Agenda Tributária" />
        <div className={styles.tables}>
          <TableBig />
        </div>
        <div className={styles.link}>
          <p>
            Se preferir acesse o site da Receita Federal (escolha o Mês e clique
            em "Data de Vencimento")
          </p>
          <Link href="https://www.gov.br/pt-br">
            <a className={styles.a} target="_blank">
              Agenda Tributária da Receita Federal
            </a>
          </Link>
        </div>
        <div className={styles.tables}>
          <TableSmall />
        </div>
      </main>
    </>
  );
}
